[package]
name = "carolus-cli"
version = "0.1.0"
edition = "2018"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
chrono = "0.4"
clap = "2.32"
failure = "0.1"
log = "0.4"
reqwest = "0.9"
simplelog = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
